name: Test

on: push

jobs:
  test:
   name: Test
   runs-on: ubuntu-latest
   steps:
     - name: Set up Go latest
       uses: actions/setup-go@v1
       with:
         go-version: latest 
         
     - name: Check out code into the Go module directory
       uses: actions/checkout@v1

     - name: Get dependencies
       run: go get -v -t -d ./...

     - name: Test code
       run: go test -v .
               